### ISSUE TITLE
Team Explorer Everywhere - Import Repository simply DOES NOT WORK

### ISSUE THREAD

**Issue by bpasham** [microsoft/team-explorer-everywhere#118]
Trying to import an existing an existing VSTS project by using Import Repository function simply fails with "Unauthorized". Is it supposed to prompt for credentials after already connected to VSTS online? It does though.
PAT created perfectly works when using directly with git clone command from console.

Alternate credentials doesn't work either

I am assuming it should NOT prompt for credentials again when already connected.

Operating System: Mac OSX 10.12
Eclipse Version: Neon.1 v4.6.1
Edition: Eclipse for Java Developers

Thanks
Bhuvan

**Comment by AlexRukhlin** [comment]
Hi,

Which version of TEE did you use? Was it 14.0.3 or the one built from the latest sources?

Thanks,
Alex

**Comment by bpasham** [comment]
TEE version: 14.0.3.201603291051
