### ISSUE TITLE
Plugin for netbeans

### ISSUE THREAD

**Issue by Chris2011** [Microsoft/team-explorer-everywhere#13]
As from the name "Team explorer everywhere" it should work everywhere, like in IntelliJ and for me in Netbeans. Netbeans is one of the 3 big Java IDE's and with a lot of more features and has a big usage in the background. So it would be nice to see such plugin for netbeans too.

Regards

Chris

**Comment by jpricketMSFT** [comment]
Hi Chris,

Thanks for providing your feedback! We really do want to reach all Java developers. I couple of things:
1) We do have a plugin for IntelliJ. You can get more info on it here: http://java.visualstudio.com/Docs/tools/intelliJ
2) We have a User Voice site where you can add or vote for the features you want. You can find it here:
https://visualstudio.uservoice.com/forums/330519-team-services/category/145260-java-tools-intellij-eclipse 

Thanks again for the feedback!
Jason

**Comment by Chris2011** [comment]
Thx for your answer: I voted for this idea: https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/11713743-tfs-plugin-for-mplabx-netbeans

I think this should be what I want. If not I will create a new Idea to add tfs-explorer-everywhere as a plugin for netbeans.

**Comment by jpricketMSFT** [comment]
That's great! This is a great way to tell us what we should work on next.

Thanks, Jason

**Comment by Chris2011** [comment]
Hey, the project is still alive, right? There are not enough votes for you, to work on such plugin for NetBeans, right?

**Comment by jpricketMSFT** [comment]
@Chris2011 - Hey Chris, Sorry this hasn't made it onto our backlog yet :(
We do monitor the user voice site, but there are still a lot of things ahead of NetBeans. 
We do have a plugin for IntelliJ and Android Studio, but that may not help you if you only work in NetBeans. Hopefully more people will vote this one up and get it to the top of the list.
-Jason
