### ISSUE TITLE
OAuth failing

### ISSUE THREAD

**Issue by romzes13** [Microsoft/team-explorer-everywhere#156]
I can't add or connect to my project from Eclipse when using "Add Team Foundation Server". After I typed my credentials in Oauth 2.0 it transfers me to my school account, then I type it again, after that it simply returns me back to previous window without any warning messages or adding any records to server list.
Not sure if it's a bug or what.

2016-12-31 02:41:39,639 INFO  [main] (com.microsoft.alm.auth.pat.VstsPatAuthenticator) Retrieving PersonalAccessToken for uri:https://myname.visualstudio.com with name:TEE: https://myname.visualstudio.com on: , and with scope:, prompt behavior: AUTO
2016-12-31 02:41:39,640 INFO  [main] (com.microsoft.alm.auth.oauth.OAuth2Authenticator) Using oauth2-useragent providers to retrieve AAD token.
2016-12-31 02:41:42,994 ERROR [main] (com.microsoft.alm.auth.oauth.OAuth2Authenticator) Failed to launch oauth2-useragent.
2016-12-31 02:41:42,995 WARN  [main] (com.microsoft.alm.auth.oauth.OAuth2Authenticator) Failed to launch oauth2-useragent.
com.microsoft.alm.oauth2.useragent.AuthorizationException: Code: cancelled Description: The browser window was closed by the user.

**Comment by luispestanajr** [comment]
I am facing this same problem.

**Comment by jpricketMSFT** [comment]
@romzes13 and @luispestanajr 
Can you send me screenshots of the problem and your complete logs? We don't know of any issues currently in this area, so any information you can provide would be helpful.
my email is jpricket <at> Microsoft.com

**Comment by luispestanajr** [comment]
Hi @jpricketMSFT, I found a solution.

In my case, I just Enable "Alternate authentication credentials".

It is located at your config options in your project.visualstudio.com, like this:

https://{MYPROJECT}.visualstudio.com/_details/security/altcreds

@romzes13, please, try this and keep us updated.

**Comment by romzes13** [comment]
I had alternate authentication credentials option on and off with no effect. Connection still not established, it simply returns me to the Oauth Mircrosoft page again. There was something on the background submitting for a split second, that' the only thing. Not  sure why I have to put my credentials even if I uploaded ssh key to my project website.

**Comment by jpricketMSFT** [comment]
@romzes13 - Can you log in through the browser? Just want to make sure that works as expected on the same machine. Can you increase the logging level for TEE and send me the debug logs? You can find some basic instructions here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/7be47259-368d-4e2a-a66a-6a08c838eac6/increasing-the-log-level?forum=tee
If that doesn't seem to work, I can provide more info.
Thanks,
Jason

**Comment by romzes13** [comment]
@jpricketMSFT Yes, I can log in through the browser. It takes me to my school account and after verification is done redirects me to my visualstudio account. I will email you my log files.
Thanks!

**Comment by romzes13** [comment]
Here's my log files.

**Comment by jpricketMSFT** [comment]
@romzes13 - I didn't receive any log files to my email and there doesn't appear to be any attached here. Can you resend?

**Comment by jpricketMSFT** [comment]
Got the logs, thanks!

**Comment by madhurig** [comment]
I believe this issue is resolved. We also have a new version of TEE that should include the fixes: [v14.114.0](http://dl.microsoft.com/eclipse). Please re-open if you continue to have the same issue.
