### ISSUE TITLE
[Question] Included Team Services SDK for Java - licensed under MIT?

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [Microsoft/team-explorer-everywhere#158]
`Team-explorer-everywhere` has included
- Team Foundation Server/Team Services SDK for Java

is it licensed under `MIT` also,
or still use special MS license as mentioned at https://www.microsoft.com/en-us/download/details.aspx?id=22616 ??

**Comment by DavidStaheli** [comment]
Hi @DzmitryHumianiuk.  Apologies for the confusion.  The MIT license is the **only** license that applies now.  It applies to Team Explorer Everywhere and everything else in this repository (the TEE plugin, the TF command line client, and the TFS SDK for Java).

**Comment by DzmitryHumianiuk** [comment]
@DavidStaheli thanks!

that means, that we can use it with our solution, licensed under GPLv3.0 :)

here https://github.com/reportportal/service-tfs we use your TFS SDK to create integration with TFS server, and post/read existing bugs into TFS.

**Comment by DavidStaheli** [comment]
Awesome, thank you!!
