### ISSUE TITLE
Team Services SDK has connection problems with TFS 2017

### ISSUE THREAD

**Issue by MichaelSchl** [microsoft/team-explorer-everywhere#160]
We use the Team Services SDK for Java (which is part of team-explorer-everywhere) in our application. With prior versions of TFS (up to TFS 2015 Update 3) it works fine. Now we tested the new released TFS 2017 with the latest available TFS SDK (version 14.111.1) and we get the following connection error:
`java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at com.microsoft.tfs.core.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:541)
	at com.microsoft.tfs.core.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2260)
	at com.microsoft.tfs.core.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1202)
	at com.microsoft.tfs.core.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:432)
	at com.microsoft.tfs.core.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:182)
	at com.microsoft.tfs.core.httpclient.HttpClient.executeMethod(HttpClient.java:428)
	at com.microsoft.tfs.core.httpclient.HttpClient.executeMethod(HttpClient.java:343)
	at com.microsoft.tfs.core.ws.runtime.client.SOAPService.executeSOAPRequestInternal(SOAPService.java:545)
	at com.microsoft.tfs.core.ws.runtime.client.SOAPService.executeSOAPRequest(SOAPService.java:444)
	at ms.tfs.services.registration._03._RegistrationSoap12Service.getRegistrationEntries(_RegistrationSoap12Service.java:106)
	at com.microsoft.tfs.core.clients.registration.RegistrationData.newFromServer(RegistrationData.java:58)
	at com.microsoft.tfs.core.clients.registration.RegistrationClient.getRegistrationData(RegistrationClient.java:617)
	at com.microsoft.tfs.core.clients.registration.RegistrationClient.getRegistrationEntries(RegistrationClient.java:144)
	at com.microsoft.tfs.core.clients.registration.RegistrationClient.getRegistrationEntries(RegistrationClient.java:129)
	at com.microsoft.tfs.core.PreFrameworkServerDataProvider.findServiceLocation(PreFrameworkServerDataProvider.java:275)
	at com.microsoft.tfs.core.PreFrameworkServerDataProvider.locationForCurrentConnection(PreFrameworkServerDataProvider.java:251)
	at com.microsoft.tfs.core.TFSTeamProjectCollection.getServerDataProvider(TFSTeamProjectCollection.java:172)
	at com.microsoft.tfs.core.TFSConnection.getWebService(TFSConnection.java:896)
	at com.microsoft.tfs.core.config.client.DefaultClientFactory$7.newClient(DefaultClientFactory.java:208)
	at com.microsoft.tfs.core.config.client.DefaultClientFactory.newClient(DefaultClientFactory.java:86)
	at com.microsoft.tfs.core.TFSConnection.getClient(TFSConnection.java:1459)
	at com.microsoft.tfs.core.TFSTeamProjectCollection.getVersionControlClient(TFSTeamProjectCollection.java:376)
	at ConnectionAdvisorSample.main(ConnectionAdvisorSample.java:92)`

We try it with our whole application, also with a simplified test program and even with one of the samples which are included (we use com.microsoft.tfs.sdk.samples.console.ConnectionAdvisorSample for our test and the prior stacktrace is from this sample). Always the same result: works with TFS 2015 update 3 but not with TFS2017.

Now the question: Should the version 14.111.1 generelly support TFS 2017 and the mentioned connection problem is possible a bug? If the mentioned version does not support TFS 2017, is there a other version available which does it or when will be such a version available? 

Thanks,
Michael

**Comment by jeffyoung** [comment]
Hi @MichaelSchl version 14.111.1 should absolutely support TFS 2017.  So we will need to investigate more into why this is happening.

Several questions:
- When you were connecting to TFS 2015 U3 _prior_ to 14.111.1, which version of the Java SDK were you using?
- To confirm, you _can_ use 14.111.1 to connect to TFS 2015 U3 but _not_ to TFS 2017.  Is that correct?
- Have you attempted to use the version of the Java SDK prior to 14.111.1 (which you could use to successfully connect to TFS 2015 U3) against TFS 2017?  I would be interested to know if that works.
- Finally, since the issue is with the connection to the server, do you know of any difference in the setup between your 2015 U3 server and the 2017 server?

**Comment by MichaelSchl** [comment]
Hi Jeff, thanks for your reply.

We use the versions 14.0.3 in the past and it works fine with TFS 2015 Update 3. The newest version 14.111.1 works also with this TFS version. 
With TFS 2017 both Java SDK version (14.0.3 and 14.111.1) brings the mentioned error. We test it first with 14.0.3 and get the mentioned error. Then we change to 14.111.1 to be up-to-date, but the result was the same.

I'm not the expert for TFS server configuration, but the only difference between the Test TFS-Servers which I see are the bindings and the endpoint which are slightly different:

TFS 2015 Update 3-Server:
http Port 8080
https Port 443
Endpoint /tfs
The web interface of the TFS server is accessible by the following URLs:
	`http://<server>:8080/tfs`
	`https://<server>/tfs`

TFS 2017-Server:
http Port 80
https Port 443
(During installation the option "HTTPS and HTTP (with redirect)" was selected ot the "Web Site Settings" in the Server Configuration Wizard, which means that every http request will be redirected to https. This redirect does not exists on the TFS 2015 Update3-Server, but in my tests I always try to connect directly to the https address, so this redirect should not matter.)
Endpoint /
The web interface of the TFS server is accessible by the following URLs:
	`http://<server>/ `(which redirect to the https-URL)
	`https://<server>/`
	
Both server use a self signed certificate which was created during the installation.

All of the mentioned URLs of the web interface works fine in the browser.

Here are the steps how I can reproduce the problem based on a example:
- I use the example ConnectionAdvisorSample (which is included in the SDK)
- I set the following settings in ConnectionSettings.java according to the TFS-Server which should be used:
	`SERVER_URL`
	`COLLECTION_URL`
	`USERNAME`
	`PASSWORD`
	`PROJECT_NAME`
- I set the environment variable `TF_ACCEPT_UNTRUSTED_CERTIFICATES=true` because I use just self signed certificates 

Result with TFS 2015 Update 3:
```Connection cache persistence store: C:\Users\User\AppData\Local\Microsoft-TEE-SDK-Sample-Vendor\Connection Advisor Sample\1.0\SampleCacheFiles
Connection configuration persistence store: C:\Users\User\AppData\Local\Microsoft-TEE-SDK-Sample-Vendor\Connection Advisor Sample\1.0\SampleConfigurationFiles
Log file persistence store: C:\Users\User\AppData\Local\Microsoft-TEE-SDK-Sample-Vendor\Connection Advisor Sample\1.0\SampleLogs
Connection time zone: UTC
Connection locale: en_US
WARN  [Thread-0] TFSConnection - The TFSConnection was closed during JVM shutdown because it was not properly closed by the creator.  The creator of the TFSConnection should close the connection when finished with it.
java.lang.Throwable: The TFSConnection was closed during JVM shutdown because it was not properly closed by the creator.  The creator of the TFSConnection should close the connection when finished with it.
	at com.microsoft.tfs.core.TFSConnection$1.<init>(TFSConnection.java:411)
	at com.microsoft.tfs.core.TFSConnection.<init>(TFSConnection.java:410)
	at com.microsoft.tfs.core.TFSTeamProjectCollection.<init>(TFSTeamProjectCollection.java:131)
	at com.microsoft.tfs.core.TFSTeamProjectCollection.<init>(TFSTeamProjectCollection.java:110)
	at ConnectionAdvisorSample.main(ConnectionAdvisorSample.java:90)
```	
Which seems to be ok (irrespective of the closing warning, which does not matter here)

Result with TFS 2017:
I get the error which I mentioned in the first post multiple times and later some other errors (which seems to be subsequent errors of the first error). I attach a textfile with the whole output. Is to long to post it here directly.
[TFS2017.txt](https://github.com/Microsoft/team-explorer-everywhere/files/707996/TFS2017.txt)

May be you could reproduce the problem based on this steps or you see something which could be wrong in my TFS configuraiton. I am ready to provide further information, if required.

Best regards,
Michael

**Comment by leantk** [comment]
Hi @MichaelSchl,

The problem looks to be with your self signed cert from the log. I was able to connect to a 2017 server with the 14.111.1 Java SDK but I was using HTTP and not HTTPS with a self signed cert. I need to setup an HTTPS  server to test further. While I do that, one thing to check on is that you imported your cert into your Java keystore. If you haven't done this, I can get you some directions. Another option is to add your 2015 self signed cert to your 2017 server since you know it has been added to the keystore. 

Thanks,
-Leah

**Comment by MichaelSchl** [comment]
Hi @leantk,
I did **not** import the cert into my Java keystore. My Java application should be able to connect to any TFS choosen at runtime without manipulating the Java keystore first. To reach this and because the application runs in a safe intranet environment we decide to accept untrusted certificates. First we reach this be using our own `HTTPClientFactory` (child class from `com.microsoft.tfs.core.config.httpclient.DefaultHTTPClientFactory`) where a overwritten method `shouldAcceptUntrustedCertificates()` always return true. Then we detect that the implementation of `DefaultHTTPClientFactory.shouldAcceptUntrustedCertificates()` did the same if the enviroment variable `TF_ACCEPT_UNTRUSTED_CERTIFICATES` is set, so that no own derived class were needed anymore. I described this way using the environment variable in my reproduction steps in my last post.
It works fine with TFS2015 using self signed HTTPS-connections, but with TFS2017 it doesn't work. In both cases the Java key store was **not** changed, that means also the self signed cert from the TFS2015 was not added to the Java key store.

**Comment by madhurig** [comment]
@MichaelSchl: Is this still an issue?
The "connection reset" error you are seeing might be related to TFS 2017 using Kerberos which is more secure over NTLM. This generally indicates a network connectivity or Kerberos configuration issue. Can you check your server event log and IIS logs corresponding to this error and see if you find something?

Thanks,
Madhuri

**Comment by MichaelSchl** [comment]
Hi @madhurig,
sorry for my late response. Yes, this is still a issue. I tried both security method (NTLM and Kerberos) without that the behaviour changed.
Currently I try to connect to the TFS via http to eliminate possible certification problems. Unfortunately my Test-TFS2017 has somehow a redirect to https, so that any request to a http-Binding will be redirected to https. We currently try to find a way to switch off this redirect so that we can connect via http. Because I'm not so fimiliar with TFS and IIS administration that seems to be no easy task.

**Comment by yacaovsnc** [comment]
@MichaelSchl I went through this thread but I couldn't find this information, so sorry if you have answered this before.  What version of Java did you use?  Thanks!

**Comment by MichaelSchl** [comment]
@yacaovsnc First I used Java version 1.8.0_51 but I've also tested it with the latest available version 1.8.0_121. Both versions have the same result as described above.

**Comment by mvodopij** [comment]
We are evaluating TFS 2017 along with Team Explorer Everywhere and are getting exact same problem when trying to add TFS server into TEE inside Eclipse. Logs show exactly the same exception and call stack.
Since we are in testing environment, I was able to test various things on the server itself with no success:

1. Changed certificate from default self signed to one issued by internal CA
2. Disabled Kerberos
3. Enabled Basic authentification
4. Using only Basic authentification

Next steps will be disabling SSL and using basic HTTP. Just need to figure out how to do that.
If you need any logs from our side, please let me know.

**Comment by jpricketMSFT** [comment]
@MichaelSchl - Hi Michael, did you ever get this working? Did the above solution help you?
Thanks,
Jason

**Comment by MichaelSchl** [comment]
Hello,

Sorry, I have not written for a while. I was busy with some another work.

In the meantime we have discovered that the problem seems to be related to the used TFS configuration. First we used "HTTPS and HTTP (with redirect)" for the setting "Settings Group" at the page "Provide the Settings for Your Application Tier Web Services" of the "Server Configuration Wizard". With this selection you get the mentioned auto redirect and the Site-Bindings does not contains "/tfs". In this configuration we got the mentioned error for HTTPS connections (http connections were not possible because of the redirect).

Then we reinstall the TFS but now with "Default" for "Settings Group". With this selection the Site-Bindings does contain "/tfs" at the end. In this configuration I got connection with HTTP and something surprising with HTTPS too (after adding a addtional HTTPS site binding). 
The only noticeable thing was that with HTTP, I had to comment out the line 92 (tpc.getVersionControlClient().getItem("$/"); ) in the used example ConnectionAdvisorSample.java. Otherwise I got a "VersionControlException: The item $/ was not found in the repository." Surprisingly, this was not necessary with HTTPS. I don't know the reason for this, but this seems only a small problem, which does not bother me at the moment because I do not use the VerisonControlClient in my productive environment. The other code works fine.
So we could make some progress in testing our application with TFS2017 but because the workability of the programm depends on the TFS configuration the Issue is not completly solved as one of our clients used exactly the Settings group which makes the trouble. So we have to test and still looking for a solution for this Settings group.

@mvodopij  We used Windows Server 2012R2 and IIS Version 8.5.9600.16384 but we see the mentioned checkbox "Require Server Name Indication". Unfortunatly we change our TFS installation, as described above, before I read your message and currently it works fine with HTTP and HTTPS as described above. So we could not test at the moment that this checkbox will solve the problem. We are currently setup a VM with a TFS2017 with "HTTPS and HTTP (with redirect)" for "Settings Group". If we had this we could test this.

**Comment by MichaelSchl** [comment]
Hello,
I was able to test it with a TFS with the "Settings Group" setted to "HTTPS and HTTP (with redirect)". And indeed it works after unchecking the mentioned checkbox "Require Server Name Indication", as mentioned above by @mvodopij .
I think we could live with this workaround. But I think it should be checked if there is a solution for TFS with checked "Require Server Name Indication", because it is a little bit confusing and time consuming, to bring the mentioned connection problems in relation to the check box and maybe there are TFS environments where the check box is mandatory.

**Comment by GregoryOtt** [comment]
Any update on this? We have reproduced this issue with the TF command and TEE on eclipse on linux against a TFS2017.2 running on HTTPS.
Disabling SNI resolve the problem. Is it the official workaround?

**Comment by eric-milles** [comment]
#310
