### ISSUE TITLE
Please can we have a permalink to the latest version of the installers?

### ISSUE THREAD

**Issue by spikerobinson** [microsoft/team-explorer-everywhere#178]
I am writing automation scripts to install the TF client on multiple hosts across our server estate. But navigating to the "latest" page at

https://github.com/Microsoft/team-explorer-everywhere/releases/latest

then requires a human being to navigate to the installers, which have different names depending on the release. Could you please create an alias or other permalink such that for example

https://github.com/Microsoft/team-explorer-everywhere/releases/latest/TEE-CLC-latest.zip

always points to the latest (stable?) version?

Thanks

**Comment by leantk** [comment]
Hi @spikerobinson,

We will look into what changes can be made to our release procedure to accommodate this but in the mean time what you can do is call this REST API https://api.github.com/repos/Microsoft/team-explorer-everywhere/releases/latest

It will give back to you back some JSON that you can parse the asset list for the "name" field to see if it contains TEE-CLC in it. Once you find that, the download link given. Let me know if that works for you.

Thanks,
-Leah

**Comment by spikerobinson** [comment]
Fantastic, I will give that a try. Thanks for the response.
