### ISSUE TITLE
NPE in CredentialsHelper

### ISSUE THREAD

**Issue by redrezo** [Microsoft/team-explorer-everywhere#179]
https://github.com/Microsoft/team-explorer-everywhere/blob/v14.111.1/source/com.microsoft.tfs.client.common/src/com/microsoft/tfs/client/common/credentials/CredentialsHelper.java#L82

There is a bug in the current version which lets the connection wizard always die on finish! I'm unable to connect to the tfs server unless there are cachedCredentials...
It seems you removed this file in master, but could you please release a hotfix version?

**Comment by DavidStaheli** [comment]
Hi @redrezo, we're working on a new release right now.  It takes a bit of time for our signing and testing process, but we're hoping to have it out by tomorrow or early next week.

**Comment by madhurig** [comment]
@redrezo: A new version of Team Explorer Everywhere is now available: [v14.114.0](https://marketplace.eclipse.org/content/team-explorer-everywhere). Please try it and let us know if you continue to have issues.

**Comment by redrezo** [comment]
Thanks, just tested it - works fine now!
