### ISSUE TITLE
Update Homebrew on Release

### ISSUE THREAD

**Issue by carlowahlstedt** [Microsoft/team-explorer-everywhere#186]
It would be great to see Homebrew get auto updated on release. It's currently several versions behind. It looks like the command line argument to update the package would be:

brew bump-formula-pr --strict tee-clc --url="[URL OF THE RELEASE]" --sha256="[SHA OF THE PACKAGE]"

I've got [a PR](https://github.com/Homebrew/homebrew-core/pull/12540) that I'm working through to understand why it failed. I couldn't use the command line update because it failed on the description that was there previously.

**Comment by jeffyoung** [comment]
Hi @carlowahlstedt.

As you know, we haven't updated HB with quite a few versions of TEE (back to 14.0.3).  We do release through our GitHub repository (which you've seen) as well as the Eclipse Marketplace.  At this point, we don't have plans to continue to update the version stored in HomeBrew.  I'm not sure if it would help or not, but there's a way you can get the latest version information from GitHub and parse the result to find the location of the CLC (specifics on that is in #178).

**Comment by carlowahlstedt** [comment]
I've got [an open PR](https://github.com/Homebrew/homebrew-core/pull/12540) trying to update to the latest version. Once I can get to the bottom of it, if you don't have plans to add a step in your release process to automate the update to HB, is there an RSS feed of sorts that occurs when a release happens? If I can figure out something, I'll see if I can set something up to automate it.

Thanks @jeffyoung for you quick reply.

**Comment by DavidStaheli** [comment]
Hi @carlowahlstedt, you could potentially use the JSON from this GitHub API to always get the latest version and detect if a new version is available:
https://api.github.com/repos/Microsoft/team-explorer-everywhere/releases/latest

**Comment by carlowahlstedt** [comment]
Perfect @DavidStaheli exactly what I was looking for. I'll see if I can't get something working. Thank you!
