### ISSUE TITLE
Eclipse - TFVC Plugin

### ISSUE THREAD

**Issue by verohiller** [microsoft/team-explorer-everywhere#193]
We work with a version of Eclipse: Luna Service Release 2 (4.4.2) and the TFVC plugin. When you edit a file from the editor, that file is not displayed within pending changes in the TFVC view Pending changes. Open and close Eclipse and there you see the changes in the view. Is there another solution? We use TEE version 14.111.1.201612142019, Visual Studio Team Services and work with local workspace.

Vero

**Comment by yacaovsnc** [comment]
Did you try "Detect Local Changes" under "Action" menu?  Does that help?  

![image](https://cloud.githubusercontent.com/assets/10119737/25856155/28fef81a-34a3-11e7-9263-af2cccb9b503.png)

**Comment by verohiller** [comment]
Thanks yacaovsnc!

**Comment by yacaovsnc** [comment]
Hmmm, that's only a workaround, we should still auto-detect.  I am glad your problem has a workaround now, but we will try to see why it didn't auto-detect.

**Comment by yacaovsnc** [comment]
What's the OS version?

**Comment by verohiller** [comment]
I followed your suggestion and then used the Deteted Change in the menu Excluded Changes, Promote. Selecting only the file to be placed in the Included Changes menu. In particular, the reported failure occurs when I add a new file to the project.
But if it should be automatic this should not? I used windows 10.

**Comment by yacaovsnc** [comment]
For adding new files, what you described is right.  You should "promote" it from the "detected changes" dialog.  

It's the first step that we must run "Detect Local Changes" to make it appear in the "Detected Changes" that I am not sure about.  I believe we should auto-detect changes on filesystem and make it appear on the "Detected Changes" list without manually run "Detect Local Changes".  

In any case I will log a backlog item to investigate this further.  You have a fairly lightweight workaround now.  :)

**Comment by renatosc** [comment]
Still seeing that issue. Changes are not automatically identified. After doing "Action" -> "Detect Local Changes" it identifies the changes (thanks @yacaovsnc for pointing that out).
