### ISSUE TITLE
com.microsoft.tfs.core.ws.runtime bundle missing lib directory in distribution

### ISSUE THREAD

**Issue by sln1803** [Microsoft/team-explorer-everywhere#206]
https://github.com/Microsoft/team-explorer-everywhere/blob/master/source/com.microsoft.tfs.core.ws.runtime/META-INF/MANIFEST.MF

lists a lib/woodstox-asl-4.0.3 directory as being on the bundles classpath:

Bundle-ClassPath: com.microsoft.tfs.core.ws.runtime.jar,lib/woodstox-a
 sl-4.0.3/stax-api-1.0.1.jar,lib/woodstox-asl-4.0.3/stax2-api-3.0.1.ja
 r,lib/woodstox-asl-4.0.3/woodstox-core-asl-4.0.3.jar

It's included in the https://github.com/Microsoft/team-explorer-everywhere/blob/master/source/com.microsoft.tfs.core.ws.runtime/build.properties

But it isn't included in the bundle in any of the update sites currently available on the https://github.com/Microsoft/team-explorer-everywhere/releases

or from http://dl.microsoft.com/eclipse/

I tracked down an older release and it is there https://www.microsoft.com/en-us/download/details.aspx?id=25125

**Comment by AlexRukhlin** [comment]
Hi,
Thanks for finding. The stale references to unused packages removed.
Alex
