### ISSUE TITLE
Assignment to Variable without Use

### ISSUE THREAD

**Issue by AppChecker** [Microsoft/team-explorer-everywhere#219]
Hi!

Please look this [code fragment](https://github.com/Microsoft/team-explorer-everywhere/blob/13584d9180f09e4f6a5cc4523efd56d787c64204/source/com.microsoft.tfs.client.common.ui/src/com/microsoft/tfs/client/common/ui/dialogs/workspaces/WorkspacesDialog.java#L67-L68):
```
        layout.marginWidth = getHorizontalMargin();
        layout.marginWidth = getVerticalMargin();
```
Probably it should be:
```
        layout.marginWidth = getHorizontalMargin();
        layout.marginHeight = getVerticalMargin();
```

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by AlexRukhlin** [comment]
Fixed

**Comment by AlexRukhlin** [comment]
Fixed
