### ISSUE TITLE
404 Error When Trying to Add a TFS Server

### ISSUE THREAD

**Issue by HelpMeSoonPlease** [Microsoft/team-explorer-everywhere#220]
Hello:  When I try to add/map a new TFS Server, I get the error in the attached PNG file.  If the attached file doesn't upload and display correctly, the Error I am receiving is:  

The SOAP Endpoint http://MY_TFS_SERVER_HOST_NAME:8080/Services/v1.0/Registration.asmx could not be contacted.  HTTP Status: 404.  

My TFS Server is on-prem and on the 2017 Update 1 version.  The TFS Server is running on a Server with an OS of Windows Server 2012 R2.  The machine I am trying this from is on the same network as the TFS Server.  The version of Eclipse I am using is the latest version (Neon).  I installed the TEE Plugin via the Eclipse Dropins Folder (C:\Users\USER ID\eclipse\java-neon\eclipse\dropins).  Eclipse picks up the TEE Plugin just fine and shows everything I would expect to see in the Eclipse Installation Details section for this Plugin.  I can open the Team Explorer View in Eclipse just fine, and start the process to add my TFS Server just fine.

From this machine (the one with the Eclipse IDE and TEE Plugin) I can connect to the same TFS environment with VS/Team Explorer.  I can also successfully connect and run commands with the Command Line Client.  However, no matter what I try I can't get this to work with the TEE Eclipse Plugin.  I have tried this using several different versions of the Plugin....all with the same result.  The TEE Plugin versions I have tried are:  14.0.2, 14.118.0 & 14.119.2.  No matter what I try I am getting the same result.  I have tried to include the collection name in the URL and leave it out.  Still the same thing.  In the latest TEE version I made sure I had my credentials entered.  Still didn't matter.  I have deleted the Plugin's cache folder (C:\Users\USER ID\AppData\Local\Microsoft\Team Foundation\4.0) before starting Eclipse each time....still doesn't make a difference.

For whatever it is worth, I am also the TFS Admin and been administering and using TFS since it first hit the market over a decade ago.  At this point I have to think there is something I may need to do administratively from the TFS end of things to get this to work, but I am at a loss.  The URL being displayed in the Plugin's Error Dialog does not seem to match up with the structure that I see in IIS on the TFS Server.  I have also attached the log (txt) file from the Plugin.  It is interesting because it also looks like there are 404 Errors being returned on a service named LocationService.asmx as well.  In that log file I replaced any occurrences of the actual server name & user name with placeholder values.  

I've got to think this works or else others would be reporting the same thing and the fact that I am getting this consistent result across all of the various Plugin versions that I have tried makes me think this is not a Plugin issue per se....but it is still interesting the CLC works fine and the Plugin does not.  

At this point, I don't know what I need to do and can't find anything in documentation or on the Internet otherwise that would steer me in the direction I need to go to get this resolved.  If anyone could please help me get going in the right direction I would be appreciative.  I have burned about 3 days trying everything I can think of and still got nowhere.

Thanks in advance!
CJ

![tee_addtfsserver_errordialog](https://user-images.githubusercontent.com/29644767/27461342-7d42aa68-577e-11e7-832e-9cf5affb4c6c.png)

[teamexplorer-plugin-2017.06.22-17.56.35.txt](https://github.com/Microsoft/team-explorer-everywhere/files/1096491/teamexplorer-plugin-2017.06.22-17.56.35.txt)

**Comment by AlexRukhlin** [comment]
Hi,
One record in the log you've provided looks suspicious for me:
(com.microsoft.tfs.core.config.httpclient.DefaultHTTPClientFactory) HttpClient configured for http://HOSTNAME:8080/tfs, authenticating as logged in user, **proxy=PROXY:80**

Do you have to use proxy? Maybe the issue is related to it?

Alex

**Comment by HelpMeSoonPlease** [comment]
Hi Alex:  Thanks!  I know I threw a lot of info in my original post.  To your comment, there was something I included in the first post that addresses your observation:  

  In that log file I replaced any occurrences of the actual server name & user name with placeholder values.

On your question of using the Proxy, there is a request I have in flight to configure my Org's IE Group Policy settings so that requests to the TFS servers on the port they are using will bypass the Proxy Server (since everything is internal).  It theoretically shouldn't make a difference but I have seen things over the years that, when the Proxy Server was removed from the equation for routing from internal to internal communications, all of the sudden things started working.  So, not ruling that out at all and will hopefully find out in the near future if that is the issue but I've got to think that there also could be more to it as well from some sort of Configuration standpoint.

Thanks again!
Chris

**Comment by HelpMeSoonPlease** [comment]
Update.....got thru the initial issue of mapping a TFS Server/Environment yesterday with a Microsoft Support Engineer on the Case I had opened up.  What had to happen was to use the FQDN (Fully Qualified Domain Name) in the URL instead of just the host name.  The engineer told me that things can get funky with Eclipse on some of the underlying network aspects.....this obviously being one of them.  After that I was able to map and connect to the Environment.  However, as we went thru verifying that the basic features within TEE worked in the 14.119.2 version, more related issues were found with core functions that may be related.  Will follow up as more develops on my Case with Microsoft.

**Comment by DavidStaheli** [comment]
Very good.  Thank you for the help, @HelpMeSoonPlease.

**Comment by MV10** [comment]
I've run into the same issue connecting TEE 14.120.0 to TFS 2017 with a slightly different error message.

If I try to set up the connection using the individual text fields, with URL `http://foo.com/`, Path `tfs`, and Port `8080` then TEE throws the error message `'The SOAP endpoint http://foo.com/TeamFoundation/Administration/v3.0/LocationService.asmx could not be contacted. HTTP status: 404`.

Instead I must enter the URL as `http://foo.com:8080/tfs/` and at that point the Path and Port text boxes are disabled in the dialog, but TEE is able to connect normally.

**Comment by HelpMeSoonPlease** [comment]
Update:  My issue was resolved this week with Microsoft Support.  Here is what the solution ended up being....

1.)Bypass the Proxy Server in communication with the TFS Environment….both from a general network perspective (i.e, your Proxy Admin and/or your Group Policy Admin will have to do this for your TFS Server's Host Name) and also within Eclipse’s Network Configuration.  Otherwise, the use of a FQDN may be necessary to establish communication to the desired TFS Environment.  Even with the use of a FQDN, and successful initial communication/connectivity with the TFS Environment, one could still encounter Proxy based errors within TEE thereafter if the Proxy is not bypassed.  This is because, in addition, TEE is built on the Apache HTTP Client Schema, which is case sensitive, so in some cases may not recognize the authentication headers being sent back from a Proxy.  IMO, if the Apache HTTP Client Schema is made to be case indifferent the whole issue with the headers and what is sent back from a Proxy becomes moot.....but that is something that is probably larger than the scope of this issue and for a different discussion.  The easiest thing for now is just to take the Proxy out of the network equation if at all possible.

2.)Make sure that all Windows/Tabs in the Eclipse IDE are restored and visible via the “Restore” button in Eclipse.  In my case, the Source Control Explorer & Work Item Query Results Tabs were for some reason hidden by default in Eclipse.  This made it appear like nothing was happening when trying to use those features of TEE.  Once I utilized the "Restore" button in Eclipse, that provided the missing magic I was looking for....and everything worked great.

I hope that this helps!  I'm closing out this issue.

**Comment by Balu123** [comment]
Hi ,
I got error in jenkins with tfs integration can u help me out from this.
FATAL: com.microsoft.tfs.core.exceptions.TECoreException: The SOAP endpoint http://tfs.casepoint.in:8080/Services/v1.0/Registration.asmx could not be contacted.  HTTP status: 404

**Comment by DavidStaheli** [comment]
Hi @Balu123, can you please log that issue in this different repo?

https://github.com/jenkinsci/tfs-plugin

You'll probably get better support there for the error you see and using the TFS Plugin for Jenkins.

**Comment by fabianoalmeida** [comment]
@Balu123 did you solve your problem? I'm suffering the same error.

**Comment by Balu123** [comment]
Can you let me know what exact you want.

**Comment by fabianoalmeida** [comment]
@Balu123 I'm trying to solve this problem (listed below) when I'm creating a pipeline on Jenkins for a TFS repo.

> Hi ,
I got error in jenkins with tfs integration can u help me out from this.
FATAL: com.microsoft.tfs.core.exceptions.TECoreException: The SOAP endpoint http://tfs.casepoint.in:8080/Services/v1.0/Registration.asmx could not be contacted. HTTP status: 404

**Comment by Balu123** [comment]
First we need to create service endpoint for it in service hooks

**Comment by fabianoalmeida** [comment]
@Balu123 I created a Jenkins service on TFS project. Is it necessary to create Service Hook for Jenkins?

**Comment by Balu123** [comment]
Service endpoint un tfs must and should

**Comment by Balu123** [comment]
I will share steps link to you

**Comment by fabianoalmeida** [comment]
@Balu123 thank you. I hope this link help me to solve this problem.

**Comment by abbbhardwaj** [comment]
Hi @fabianoalmeida and @Balu123.

Could you please send me the link to help solve this similar issue you guys just discussed. It is about Jenkins and TFS service hook creation.
