### ISSUE TITLE
Refreshing TFS Server - hung or times out

### ISSUE THREAD

**Issue by jaypit** [microsoft/team-explorer-everywhere#231]
When opening Eclipse any open project causes "Refreshing TFS Server" and either hands the instance and does not work, or times out. I am able to use Eclipse while the TFS Server is refreshing to code. But to LOCK a project or any of the TFS functions are not usable until it completes or fails. I can sometimes kill the refresh and it will work fine for a while until a Refresh needs to occur. I've attached some sample of the build it gets stuck on.

Question 2: The plug-in is installed on a custom version of Eclipse provided by a software vendor that has custom setups. Could the plug-in need something this custom version of Eclipse does not provide (though I can get it to work, not smoothly)? What is the minimum Java version needed for the plug-in? What is the minimum access in TFS I might need?  

New to this forum btw.

![buildworkspacetfs](https://user-images.githubusercontent.com/31513480/29930676-b151e26e-8e34-11e7-9495-04a2e4ba27ef.JPG)

**Comment by eric-milles** [comment]
#310
