### ISSUE TITLE
Exception with JDK9 installed and JDK8 as default.

### ISSUE THREAD

**Issue by alandamatta** [microsoft/team-explorer-everywhere#235]
I was having an exception with jdk9 even with jdk8 as default java home.
Follow the exception:
Unable to create view: Plug-in "com.microsoft.tfs.client.common.ui" was unable to instantiate class "com.microsoft.tfs.client.common.ui.views.TeamExplorerView"

For ones who has this problem in the future, to solve this i unninstall jdk9 and go to:
Help>Team Explorer Support>Platform Log>clear .log file and restart eclipse.

**Comment by rcnicke** [comment]
I had the same problem today and spent a good many hours to solve it. But I did, solution described here:
[TEE CLC not working on Mac](http://expicon.se/2017/10/13/tee-clc-not-working-on-mac/)

**Comment by rcnicke** [comment]
Sorry, reply was on the wrong thread

**Comment by SgtJorny** [comment]
Thank you!!!!
