### ISSUE TITLE
JDK 9  - No output on stdout/stderr

### ISSUE THREAD

**Issue by spoorcc** [microsoft/team-explorer-everywhere#237]
With following versions:

- MacOS 10.7
- Tee-clc 14.123.1
- Java 1.9.181

When running `./tf` with any command, there is no output whatsoever in the terminal.
When downgrading to java 1.8.144 everything works as expected.

The command `java -version` does return output

**Comment by rcnicke** [comment]
Trying again:
I had the same problem, has to do with Java 9.
Problem and solution described here: [TEE CLC not working on Mac](http://expicon.se/2017/10/13/tee-clc-not-working-on-mac/)

**Comment by spoorcc** [comment]
Thanks, that might solve it. I'm pressed for time, so I downgraded to Java 8 for now.
This could then be fixed in [clc-launcher](https://github.com/Microsoft/team-explorer-everywhere/blob/c1012bc8619e265dcb6ce4c755d98df17064e5bc/source/com.microsoft.tfs.client.clc/scripts/clc-launcher) if somebody wants to make the world a better place by adding `--add-modules java.xml.bind` to the `exec java` call.

**Comment by axelgenus** [comment]
This issue affects also the Windows version and the proposed solution linked by rcnicke works also on Windows.

My environment:
- Windows 10 Enterprise (64 bit)
- Java Development Kit 9.0.1+11 (64 bit)
- TEE-CLC 14.123.1

**Comment by EricTheRed-VT** [comment]
I have the same env as @axelgenus , but I can't get @rcnicke 's fix to work.
I added the flag 
`java –-add-modules java.xml.bind -Xmx2048M -cp...` 
but command prompt is throwing an error: 
`Error: Could not find or load main class GÇô-add-modules                                                                Caused by: java.lang.ClassNotFoundException: GÇô-add-modules `

**Comment by YasserMojahed** [comment]
I have upgraded my Android Studio to version 3 then I faced the same issue with TF.
first I added this "--add-modules java.xml.bind" to "tf"
but it still gave me the same exception.
I added it to "tf.cmd" then it worked.
I hope that wont has bad effects on "commit changes", "show diff" and other TFS - android studio functions

**Comment by eric-milles** [comment]
`java.xml.bind` dependency removed in release 14.135.0
