### ISSUE TITLE
Authentication Error when using Eclipse to connect to TFS GIT repository

### ISSUE THREAD

**Issue by mtshatby** [microsoft/team-explorer-everywhere#240]
We are running into an authentication error when trying to use eclipse to connect to a TFS Git repository (TFS 2015). Looking up the FAQ indicates that this is a known issue, and suggests using cntlm as a solution. It also indicates that this will be resolved in future releases. How do I get a status of where that is at? We had trouble getting past this error even with cntlm installed. Please advise, any help is appreciated.

**Comment by mtshatby** [comment]
Attached are the logs for the authentication. The latest log is the one that shows the error. Please note that I had been switching between TEE 12.X and TEE14.X, and that’s why in some of the logs, you may see a successful authentication. However, eventually even 12.X also failed! 


[Logs.zip](https://github.com/Microsoft/team-explorer-everywhere/files/1484130/Logs.zip)

**Comment by liuquanzhang** [comment]
TEE-CLC-14.134.0 身份验证失败是什么原因呢
