### ISSUE TITLE
[TEE - Eclipse] Not Showing Source Control Explorer

### ISSUE THREAD

**Issue by xom-pschiess** [microsoft/team-explorer-everywhere#244]
I have a strange issue where when I connect to my TFS using the Eclipse TEE plugin, occasionally certain team projects will not show the 'TFVC Source Control Explorer' or 'TFVC Pending Changes' options. For reference - my team project contains both Git and TFVC repos and the TEE plugin is only showing the options for Git Repos. Any help would be greatly appreciated.

**Comment by beowoolf** [comment]
Do you know anything in this topic how to solve this problem, because I also have a similar problem?
