### ISSUE TITLE
Performance issues with TFS2017.2

### ISSUE THREAD

**Issue by huntantr** [microsoft/team-explorer-everywhere#249]
Environment: TFS 2017 Update 2 RTM
 
Recently we have upgraded our TFS server from TFS 2015 to TFS 2017.2. After that, we are experiencing that the TFS plug-in for Eclipse, Team Explorer Everywhere version 14.123.1 is slow. All check-in/check-out are taking minimum 5 minutes, and work items are not loading. IDE not responding whenever a work items query is involved. Due to this builds are also taking longer to complete. 
 
With the previous version of Team Explorer Everywhere 14.0.3, check-in/check-out performance seems better but still work items are not loading.

We have also noticed that TEE is using the 4.0 interface instead of 7.0. We have determined this by clearing the TFS cache and when running just TEE it always creates the 4.0 cache folder.

Any ideas on why we are experiencing performance issues with TFS2017? We were not with TFS2015.

**Comment by eric-milles** [comment]
#310
