### ISSUE TITLE
Eclipse aborts installation of TEE 14.123.1

### ISSUE THREAD

**Issue by MatRue** [microsoft/team-explorer-everywhere#252]
Hi,

today I have tried to install TEE 14.123.1 but Eclipse aborts the installation and showed the following message:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Team Explorer Everywhere 14.123.1.201709051450 (com.microsoft.tfs.client.eclipse.feature.feature.group 14.123.1.201709051450)
  Missing requirement: Team Explorer Everywhere EGit Client Support 14.123.1.201709051450 (com.microsoft.tfs.client.common.ui.teambuild.egit 14.123.1.201709051450) requires 'bundle org.apache.commons.logging 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Team Explorer Everywhere 14.123.1.201709051450 (com.microsoft.tfs.client.eclipse.feature.feature.group 14.123.1.201709051450)
    To: com.microsoft.tfs.client.common.ui.teambuild.egit [14.123.1.201709051450]
```

I am using Eclipse Mars2 4.5.2.

It seems that the bundle 'org.apache.commons.logging 0.0.0' is missing.
Currently I have no idea where to get the missing bundle and how to install it.
May be you could provide me some information how to fix this issue.

Regards
Matthias

**Comment by tugrulguclu** [comment]
Hello

I`m having a similar problem. Has anyone found a solution for this ? 

Missing requirement: Team Explorer Everywhere EGit Client Support 14.134.0.201804261733 (com.microsoft.tfs.client.common.ui.teambuild.egit 14.134.0.201804261733) requires 'bundle org.apache.commons.logging 0.0.0' but it could not be found
