### ISSUE TITLE
tf CLI never prints output on Windows 10, Mac OS High Sierra

### ISSUE THREAD

**Issue by latentstops** [microsoft/team-explorer-everywhere#255]
Steps:
1. Downloaded TEE-CLC-14.123.1.zip 
2. Extracted `%USERPROFILE%\Documents\TEE-CLC-14.123.1`
3. cd `%USERPROFILE%\Documents\TEE-CLC-14.123.1`
4. executed `tf` command - no output
5. executed `tf.cmd` command - no output
6. executed `tf eula` command - no output

Microsoft Windows [Version 10.0.14393]

**Comment by trumbitta** [comment]
Same thing on Mac OS High Sierra 👎

**Comment by jamescw** [comment]
+1 high sierra

**Comment by cynical89** [comment]
@trumbitta & @jamescw 

The answer in this link solved this issue for me on High Sierra.
https://expicon.se/2017/10/13/tee-clc-not-working-on-mac/

Without clicking the link, line 147 of the tf file you need to add `--add-modules java.xml.bind` after `exec java`. The following code is how it looked in my file while it was working.

```
exec java --add-modules java.xml.bind -Xmx2048M -classpath "$CLC_CLASSPATH" $TF_ADDITIONAL_JAVA_ARGS \
	"-Dcom.microsoft.tfs.jni.native.base-directory=$BASE_DIRECTORY/native" \
    $RANDOM_DEVICE_PROPERTY com.microsoft.tfs.client.clc.vc.Main "$@"
```

**Comment by trumbitta** [comment]
@cynical89 yep for me too. Sorry I forgot to come back and update my comment!

**Comment by latentstops** [comment]
Replacing `exec java` with `exec java --add-modules java.xml.bind` in `tf` file solves the problem on Windows 10 also. Thanks a lot!!!

**Comment by trumbitta** [comment]
@latentstops I think you should keep this issue open until they don't fix it in the source code :)

**Comment by kiasta** [comment]
Adding exec java --add-modules java.xml.bind to the tf file gives me this error:

> Error occured during initialization of boot layer java.lang.FindException: Module java.xml.bind not found

Any ideas? I have installed java 8u121 just so I can have a version that is supposed to work without using this fix. I'm on macOS Mojave (wasn't working in High Sierra either)

**Comment by filippoitaliano** [comment]
There's any plan to fix this issue?

**Comment by KrisJanssen** [comment]
This issue is still not resolved... in fact, it would seem that in more recent version of the JDK, the required JAX-B Api's are not even available at runtime anymore...

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

Is something being done to address this?

**Comment by ForNeVeR** [comment]
One possible workaround would be to define an environment variable `TF_NOTELEMETRY=TRUE`. According to my experiments, it should disable the telemetry and thus the need for `javax.xml.bind`. Could you try it, please?

**Comment by msasso69** [comment]
Same problem on Linux, but with TF_NOTELEMETRY=TRUE (and java 11.0.2) works for me, Thanks

**Comment by OttoG** [comment]
The TF_NOTELEMETRY=TRUE should be the best workaround in most cases, but if for some reason solutions that require editing of configuration files or the tf/tf.cmd script file are not desired, it is also possible to download a JAR package and add it to the lib directory of TEE.

The following search should produce links to the current version of the jaxb-api package:

https://search.maven.org/search?q=g:javax.xml.bind%20AND%20a:jaxb-api

Download it as a JAR file (currently called "jaxb-api-2.4.0-b180830.0359.jar") and place the file in the TEE lib directory. This workaround seems to be effective under JDK 12.0.2 on macOS as well as Windows 10.

**Comment by HTMLangdon** [comment]
Just so that this is completely clear for others who might not have experience.

If you have recently installed or updated to the latest version of Java/JDK/JRE (12 something?)
and are trying to run:

`tf`

you will [possibly] get no output, no readout - nothing. There's actually a behind the scenes error occurring, which are being logged in .log files.
Here are a list of terminal commands to check out the logs, and to update your tf shell script to fix the issues:


```
#cd to tf error log(s) dir:
cd ~/Library/Application Support/Microsoft/Team Foundation/4.0/
```

```
#open a finder window at the location of tf shell script:
#right click 'tf' and open with > VSCode, TextEdit, Sublime,  w/e floats your boat....
open /usr/local/Cellar/tee-clc/14.134.0/libexec/

```

```
#copy/pate this to replace what is currently in your 'tf' shell script file:
# *Note: MAKE A BACKUP, or comment your original file contents using the hash prefix
#  <-- like him =]
#!/bin/bash
TF_NOTELEMETRY=TRUE
exec "/usr/local/Cellar/tee-clc/14.134.0/libexec/tf" "$@"
```

**Comment by thomasfdm** [comment]
> One possible workaround would be to define an environment variable `TF_NOTELEMETRY=TRUE`. According to my experiments, it should disable the telemetry and thus the need for `javax.xml.bind`. Could you try it, please?

This worked for me on OSX 10.14.6

**Comment by QuytNguyen** [comment]
> One possible workaround would be to define an environment variable `TF_NOTELEMETRY=TRUE`. According to my experiments, it should disable the telemetry and thus the need for `javax.xml.bind`. Could you try it, please?

This worked, tks !!! macOS Catalina, java 1.8.0_251

**Comment by yehudamakarov** [comment]
setting `TF_NOTELEMETRY=TRUE` worked for me on mac

**Comment by Mrugendra27** [comment]
For me I had to download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
into the TF_CLC_HOME/lib directory where all the jars reside for the TEE-CLC.
Downloading any version >1.7.30 does not work.
