### ISSUE TITLE
https://java.visualstudio.com/Docs/tools/eclipse is 404

### ISSUE THREAD

**Issue by ilovezfs** [microsoft/team-explorer-everywhere#262]
The url referenced in the readme https://java.visualstudio.com/Docs/tools/eclipse is 404

**Comment by nschonni** [comment]
Opened https://github.com/MicrosoftDocs/vsts-docs/issues/685 since https://docs.microsoft.com/en-us/vsts/java/download-eclipse-plug-in?view=vsts appears to be the new page, but doesn't include the old install instructions
