### ISSUE TITLE
Update description to include TFS 2018 (Eclipse IDE)

### ISSUE THREAD

**Issue by rhundhausen** [microsoft/team-explorer-everywhere#267]
In the Help > About Eclipse IDE page, it shows TFS versions from 2012 to 2017, but omits 2018.

![tee2018](https://user-images.githubusercontent.com/4683537/40738781-b36ecc4e-6401-11e8-95b6-07c886b10e22.png)

**Comment by nschonni** [comment]
Looks like it's probably this that needs to get updated https://github.com/Microsoft/team-explorer-everywhere/blob/master/source/com.microsoft.tfs.client.clc.feature/feature.properties
