### ISSUE TITLE
java.lang.ClassNotFoundException: com.microsoft.alm.visualstudio.services.webapi.ApiResourceVersion$Version

### ISSUE THREAD

**Issue by ketan** [microsoft/team-explorer-everywhere#268]
It seems that the latest TFS SDK (14.134.0) does not package the said class, loading the `TFSTeamProjectCollection` class seems to load the superclass `TFSConnection` which references `com.microsoft.alm.visualstudio.services.webapi.ApiResourceVersion.Version`

The sdk jar does not contain the said class.

**Comment by armchairdeity** [comment]
Hey dude... this class is provided by one of the other downloads in the project... if you download and unpack `TEE-CLC-14.134.0.zip`, you'll find the Visual Studio client in `alm-vss-client-15.105.0-SNAPSHOT.jar` in the lib folder. `com.microsoft.alm.visualstudio.services.webapi.ApiResourceVersion.Version` is part of that package.

Just drop that jar in your class path and you should be good... at least on this error message.

**Comment by ketan** [comment]
Are there other jars I should drop in? I used to be able to run this thing with a single jar earlier.

**Comment by eric-milles** [comment]
There are transitive dependencies in some of the plugins:

![image](https://user-images.githubusercontent.com/18193802/145616798-e13a3e77-6685-4fe5-960b-3744abf0e20b.png)

There are also transitive dependencies of these in a couple cases.  For example, slf4j jars in the core project.
