### ISSUE TITLE
macOS 10.13.5

### ISSUE THREAD

**Issue by ronbok** [microsoft/team-explorer-everywhere#274]
I've installed VS Code for macOS.  Added the TFVC Extension into VS Code.  Installed Java 8.1, JDK 10.1.  Downloaded TEE-CLC and unzipped it.  Confirmed Java was running by typing java -version and got back:

java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

No idea why I'm seeing 18.3, when I downloaded jre-8u171-macosx-x64.dmg, but whatever...

Tried to get even the most basic tf command to work in Terminal.  Nothing.  No response other than it returning my cursor to the next line.  I deleted the folder where I extracted the .zip.

I then installed Xcode and Brew.  Ran the 'brew install tee-clc', and it completed successfully.   Tried again to run the most basic of tf command 'tf' and 'tf eula'.  Again no response.  

Does this work on macOS at all?

I'm trying to eventually connect this to a VSTS instance, not TFS on-premises.

**Comment by ronbok** [comment]
Actually it does.  Just don't install the JDK 10.1, make sure you match the JDK version of 8 171 and then it works fine.

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by nfantone** [comment]
This no longer works in JDK 11, as `java.xml.bind` module was scheduled for deprecation and removed.

**Comment by eric-milles** [comment]
The telemetry feature, which made use of `java.xml.bind` was removed in release 14.135.0
