### ISSUE TITLE
Ignore files not working in Eclipse (Neon 3) 

### ISSUE THREAD

**Issue by fhx** [microsoft/team-explorer-everywhere#279]
Hi Team Explorer Everywhere,

love your tool and been using it for years :-) 

Im having problems with a multimodule Maven project in Eclipse (neon3) where .tpignore and .tfignore (old-style) are not honored, the files ignored show up in my pending changes view making it cumbersome to checkin.

**.tpignore content**
# (Old style) TFS ignore file
target
bin
!*debug
.classpath
.project

**.tpignore content**
# Team Explorer Everywhere ignore file
\Q/.project\E
\Q/.classpath\E
\Q/target/\E.*

Ive attached the .ignore files and a screenshot of the pending changes. 

![tfs-bug](https://user-images.githubusercontent.com/834697/45016267-6aaf8880-b024-11e8-81fd-26233dc3c046.png)

**Comment by fbertini** [comment]
Hello, 

I have the same problem here on Eclipse. Also, in the "Team Synchronizing" perspective, the Synchronize view, shows pending files even if they are excluded in Window->Preferences->Team->Ignored Resources:
![immagine](https://user-images.githubusercontent.com/12632517/66759068-d4dd6280-ee9f-11e9-9c06-ba4dbdb7ba4f.png)

I really have no Idea why this is happening and some other resources are being ignored as expected.
Team Explorer Everywhere	14.134.0.201804261733

**Comment by aaangulowork** [comment]
tpignore files are differ from tfignore files as they use PCRE characters.
\Q and \E specify quoting in PCRE. 
Everything between \Q and \E is automatically escaped.

\Q/tests/bin/\E.*
\Q/tests/gen/\E.*
\Q/obj/\E.*
\Q/target/\E.*
\Q/.settings/\E.*
\Q/gen/\E.*
\Q/bin/\E.*
\Q/\E.*.jar
\Q/\E.*.war
\Q/\E.*.ear

\Q/target/E.* is looking for a target folder under the root folder and then all folders underneath. This is why it allows datasync-configuration\target

**Comment by ianwilliams1** [comment]
Could someone from TEE team explain
- when was this syntax change made
- where the [change documented](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/gg413275(v=vs.100)?redirectedfrom=MSDN#tpignore) ; it certainly doe snot seem not be noted in the [RELEASE NOTES](https://github.com/microsoft/team-explorer-everywhere/releases) of any release. 
- are both syntaxes acceptable? ie: is this backwards compatible? ([Semantic versioning](https://semver.org/) should also apply if not)

We have over 600 TFVC repositories with upwards of 3000 branches, each one with a tfignore and tpignore file pair at the root. Are we really expected to revisit all those files ?

**Comment by eric-milles** [comment]
The new syntax is regex on path of file(s).  `\Q` and `\E` are start and end of quoted, which you don't need to use.  I think it was described in http://kb.teamprise.com/article/view/38 but that is a dead link now.  The model is here: https://github.com/microsoft/team-explorer-everywhere/tree/master/source/com.microsoft.tfs.client.eclipse/src/com/microsoft/tfs/client/eclipse/tpignore

**Comment by eric-milles** [comment]
One item of interest: the `.tfignore` files are used by local change detection -- not sure if this includes the _Team Synchronizing_ perspective.  `.tpignore` files are used more generally by the eclipse TFS UI to prevent pending changes.  But `.tpignore` are not used by the local change detection.  I'm not sure why this is and I'm investigating further.

Regarding `.tpignore` files format, you don't need to use the `\Q` and `\E` style that the UI produces.  We have a simple series of patterns:
```
/.externalToolBuilders/.+
/.settings/.+
/.classpath
/.project

/bin.*
/build.*
/derived/.*
/dist/.*
/[Ll]ogs?/.*
/TestResults/.*
/WebContent/Manifest.xml
/WebContent/WEB-INF/lib/.*
/WebContent/WEB-INF/classes/.*

.*/junit[^/]*\.properties
.*\.hprof(\.txt)?
.*\.log(\.\d+)?
.*\.class
.*\.jpage
.*\.lck
.*\.tmp
```
