### ISSUE TITLE
Eclipse TEE login loop after Azure DevOps Rebranding

### ISSUE THREAD

**Issue by schwarzjoseph** [microsoft/team-explorer-everywhere#281]
Trying to login with the Eclipse (Oxygen) TEE plugin results in a login loop. I try to connect to our account with the URL https://dev.azure.com/our-organization-name/

I get prompted to visit the authentication page at https://microsoft.com/devicelogin  with a code, but after authenticating with the code, it simply loops back to the sign in completion page with a new code.  Happens when I try to authenticate with either Chrome or Edge. 

TEE plugin is v  14.134.0.201804261733

**Comment by jrbriggs** [comment]
Hi @schwarzjoseph -- can you try using a PAT to auth?

**Comment by rroman81** [comment]
@jrbriggs I am having the same issue with client dev team.  Using PAT directly also causes the same issue.  When entering the PAT in the dialog, it appears to succeed, but when clicking ok to authenticate, we are prompted again to visite authentication page.

They are using Eclipse 2018-09 Windows build, and TEE plugin v14.134.0.201804261733.

**Comment by eric-milles** [comment]
I updated the auth library from 0.6.0-SNAPSHOT to 0.6.4 and the first sign-on attempt was able to retrieve the access token.  I will package a new release shortly.
