### ISSUE TITLE
"Git Repositories" section not visible in TEE for Eclipse 2018-09 version

### ISSUE THREAD

**Issue by Hoyg** [microsoft/team-explorer-everywhere#283]
Hi,  I am unable to see "Git Repositories" or even TFVC source control section under the latest TEE for Eclipse 2018-09 version Build-id: 20180917-1800. Am I missing any configuration or is it a bug?

**Comment by trks1970** [comment]
Same for me. Did a clean install of Eclispe 2018-09, install TEE from marketplace. No Git Repositories entry.

**Comment by tim6string** [comment]
I am seeing this issue as well.

**Comment by teejam2** [comment]
I am also having this issue

**Comment by looufa** [comment]
I am also having this issue

**Comment by andreasbisiach** [comment]
Same problem, cannot see "Git Repositories"
Eclipse IDE for Enterprise Java Developers.

Version: 2018-12 (4.10.0)
Build id: 20181214-0600

Team Explorer Everywhere
Version 14.134.0

**Comment by gnumarco** [comment]
Same problem here, since many months with both Eclipse-jee-2018-09 and Eclipse-jee-2018-12.
Anyone actually cares about this issue?

**Comment by abigailknoble** [comment]
Same problem. any resolution found?

**Comment by sladeswan** [comment]
I haven't found a resolution but have wound back to Eclipse Photon and the Git Repositories display with TEE 14.134.0.  So it would appear that TEE would need to be updated to work with newer releases of Eclipse.  I experienced the same problems above with 2019-03 release.

**Comment by snebaybay** [comment]
Hello do we have any updates on this issue? Has anyone been able to successfully use TEE with Eclipse?

**Comment by trks1970** [comment]
Actually, I was able to use Azure DevOps Repos with Eclipse 2018-12, when
NOT installing TEE. Also, do not install git-flow for eclipse.

Sneha <notifications@github.com> schrieb am Fr., 19. Juli 2019, 15:50:

**Comment by pwhirley** [comment]
Try uninstalling the TEE language pack.  I was having the same problem with 2019-06 Eclipse but not with a separate 2019-03 Eclipse instance.  I compare the installed plug-ins and noted that the one which was working did not have the TEE Language Pack installed.  When I uninstalled the TEE Language Pack from the 2019-06 instance of Eclipse, my Git repositories showed up in TEE.

**Comment by seanValtech** [comment]
Uninstalling the TEE language pack fixed it for me.
