### ISSUE TITLE
-Xmx2048m too big for RaspberryPi

### ISSUE THREAD

**Issue by DotNetPat** [microsoft/team-explorer-everywhere#287]
Heya Guys!

I am running an Azure Pipeline Agent on my Raspberry Pi 3b and I had problems with tf that are caused by the -Xmx2048m switch for the Java-VM. I fixed my issue by changing it to -Xmx512m and it seems to work fine for me.

So what about changing that switch, so tiny ARM-Devices like Raspberry could also use TEE?
Best Regards
Patrick

**Comment by brunoborges** [comment]
I'm curious to know why 2GB is hardcoded.
