### ISSUE TITLE
can't use tfs's java sdk library along with jackson dependency

### ISSUE THREAD

**Issue by sify21** [microsoft/team-explorer-everywhere#293]
I discovered that jackson is bundled within tfs's library jar, and if I add jackson dependency along with tfs library, an error will occur:
`java.lang.SecurityException: class "com.fasterxml.jackson.annotation.JsonCreator$Mode"'s signer information does not match signer information of other classes in the same package`
Are there any solutions to avoid this problem?

**Comment by eric-milles** [comment]
You can replace `...\plugins\com.microsoft.tfs.core_14.136.0\libs\jackson-core-2.4.1` with whatever version of jackson you want.  Just be sure to fix the links in `...\plugins\com.microsoft.tfs.core_14.136.0\META-INF\MANIFEST.MF`
