### ISSUE TITLE
Unable to view history after upgrading to latest Eclipse 2018-12

### ISSUE THREAD

**Issue by mpenningroth** [microsoft/team-explorer-everywhere#297]
I recently upgraded to Eclipse 2018-12 (4.10.1) Build id: 20181214-0600.
After the upgrade I can no longer view my tfs history, it gets a NPE .

Initial version of Eclipse 2018-12 worked fine.

**Comment by IvanBaricic** [comment]
This is a duplicate issue of #290, where you could find more details about this "bug" (deprecated classes as TableTreeViewer were removed from the newest version of the Eclipse; but still exist in the plugin).
