### ISSUE TITLE
Not able to connect Azure DevOps through eclipse using team explorer 

### ISSUE THREAD

**Issue by griosha** [microsoft/team-explorer-everywhere#310]
one of the customers was not able to connect to Azure DevOps using team explorer.
They were using the photon version of the eclipse. The commit and push functionality is working but the rest of the functionality does not work.
Below is the error message.
![TEE1Capture](https://user-images.githubusercontent.com/36469621/69662755-f8084e00-10aa-11ea-9a14-12f25b1ca93c.PNG)
Please help us onthis issue.

**Comment by eric-milles** [comment]
Best I can tell from the code, there are a number of buffer layers around the HTTP/SOAP responses. The responses are gzip encoded to reduce network traffic. The SOAP client copies the XML into a local buffer using `XMLStreamReader` and `XMLStreamWriter`. If this copy takes a long time -- and I think if the compression is good -- there is not enough demand on the server socket for data and it closes the connection. Disabling the gzip causes more back and forth and seems to be enough to keep the connection alive.

You can disable gzip compression be setting system property `teamexplorer.soap.disable-gzip` to true.  Easiest way to so this is to add it to the end of `eclipse.ini` file.

**Comment by eric-milles** [comment]
There are likely 2 issues here:
1. client does not enable keep-alive socket option -- gzip off is a hack to generate more traffic in lieu of proper keep-alives
2. when reading SAOP response, client copies payload into buffer; if size >8MB it will write to temp file -- this file writing is unbuffered (aka inefficient)

You can delay or disable file fallback by increasing the heap size limit `com.microsoft.tfs.fasttempstream.heaplimit` to something greater than 8MB.
