### ISSUE TITLE
Unable to execute historyaction

### ISSUE THREAD

**Issue by LaughingLUO** [microsoft/team-explorer-everywhere#316]
When I check the history, I report an error directly.
![image](https://user-images.githubusercontent.com/22276108/78765712-f46ec700-79ba-11ea-996e-c0ad18f9c61a.png)

Eclipse Version:2019-12 (4.14.0)
![image](https://user-images.githubusercontent.com/22276108/78765170-34817a00-79ba-11ea-9699-5436b3107615.png)
Team Explorer Everywhere Version:  14.134.0.201804261733
![image](https://user-images.githubusercontent.com/22276108/78765584-c8534600-79ba-11ea-88c4-9aee6d58dac5.png)

**Comment by eric-milles** [comment]
This is fixed in 14.135.0
