### ISSUE TITLE
tfs not working on android studio using mac os catalina 

### ISSUE THREAD

**Issue by innocentmujahid** [microsoft/team-explorer-everywhere#317]
the specified path does not lead to a valid tf executable, I changed the xmx but did not help me

**Comment by ForNeVeR** [comment]
Could you please clarify, which path have you entered?

**Comment by innocentmujahid** [comment]
i just unzip TEE-CLC-14.134.0 and browse tf.cmd from android studio

**Comment by ForNeVeR** [comment]
On macOS, you should point it to `tf` file, not `tf.cmd`.

`tf` is a shell script for Unix-like OS, `tf.cmd` is only for Windows.

**Comment by innocentmujahid** [comment]
thank you so much now I am facing that issue “libnative_misc.jnilib” cannot be opened because the developer cannot be verified.  macOS cannot verify that this app is free from malware.

**Comment by ForNeVeR** [comment]
You have a couple of variants here:
1. You can disable the code signature checks system-wide (I sincerely cannot recommend that), but I can't remember exact way to do this off the top of my head.
2. You can try installing a newer command line client from JetBrains (as a necessary disclaimer, I'm the maintainer of that repository): https://github.com/JetBrains/team-explorer-everywhere/releases

   That is a fork of this repository used for some parts of Azure DevOps IntelliJ build process, and there's a command line client with native dependencies removed (exactly for the purpose of avoiding troubles with macOS verification).

**Comment by innocentmujahid** [comment]
thank you so much this worked perfectly
