### ISSUE TITLE
TFS Sdk is not fetching complete projects list using WorkItemClient

### ISSUE THREAD

**Issue by kuldeep-singh-blueoptima** [microsoft/team-explorer-everywhere#318]
TFS Server version: 15

There are 2 repositories in this server, which are under same project and same collection. Say the repositories are repo1 and repo2. Both repositories have read permissions for a user, say, abc. 

On client side, we use TFS Java SDK to fetch repository information. However, it doesn't seem to be working properly. There are a few scenarios as mentioned below: 

1. When we use username & password with TFS sdk to get projects, it returns only one repo. It was expected to return both repos. 
2. When we use username & PAT (full access), it simply fails with "Permission denied by server".
3. When we try on CLI using curl command, it lists both repositories. This curl works with both password and PAT. It refers that the both repos are indeed accessible, however tfs sdk seems to have some issue listing them. 

Can you please help if there is any fix for this, or any way to make it work?

Note: We can't use curl in our code, we'll need to prefer solution based on TFS sdk only.

**Comment by eric-milles** [comment]
I needed to have permissions changed from "Stakeholder" to "Basic" on the ADO side to get the full list again.
