### ISSUE TITLE
Cannot create new workspace in WSL using CLC

### ISSUE THREAD

**Issue by HolisticDeveloper** [microsoft/team-explorer-everywhere#324]
I'm using WSL2 with an Ubuntu 18.04 release. I've downloaded TEE CLC 14.135.0 and have successfully accepted the EULA. However, I can't seem to create a workspace successfully. I don't get any error returned but the workspace is not created. Should I also be prompted to authenticate?

```
$ tf workspace -new test -collection:http://server.domain.local:8080/tfs/DefaultCollection
$ tf workspaces
No local workspaces found.
```

**Comment by masoudmghd** [comment]
I don't know why but in latest release(14.35) two library is missing.
Just copy slf4j-api-1.7.19.jar and slf4j-log4j12-1.7.19.jar from a older release(14.134) lib folder to your desired release lib folder.

FYI , there is logs in ~/.microsoft folder. which you could use.
