### ISSUE TITLE
Download / Clone Project

### ISSUE THREAD

**Issue by ertanyildiz** [microsoft/team-explorer-everywhere#328]
Hi. How can I download/clone project to my device using SDK? I did not find anything about my issue. Is there any code sample that downloads project from TFS server? Thanks.

**Comment by ForNeVeR** [comment]
I afraid there's no clear guidance on how to do it, but here's what I would do.
1. Take a look [here](https://stackoverflow.com/a/41577572/2684760) on how to do it with the command-line client (`tf.cmd` usage from the CLC package is pretty similar)
2. Check code for the corresponding commands in the command-line client (i.e., say, `CommandWorkspace`, `CommandWorkfold`, `CommandGet`)
3. Call the same code in your class that uses SDK

You may find some samples on how to use SDK in [the Azure DevOps IntelliJ plugin](https://github.com/microsoft/azure-devops-intellij/blob/1cdaf0aab461096ba5e0f25ce348d1bafe6b2ff7/client/backend/src/main/kotlin/com/microsoft/tfs/TfsClient.kt)¹ (though there's no implementation of clone/checkout there yet).

¹ Totally not an spam/advertisement, but a Microsoft-managed project.
