### ISSUE TITLE
TFVC WSL can't create new local workspace

### ISSUE THREAD

**Issue by loviji** [microsoft/team-explorer-everywhere#329]
I use Ubuntu WSL on Windows 10 OS.
In Ubuntu 20.04 LTS I have docker installed for creation docker images. 
Then we have on premise Azure Devops Server 2019. 
There have source codes in ***git*** and also in ***tfvc***.
With git we have not problems, it's more native with Linux. But with ***tfvc*** I can't create workspace for getting code in next steps.
As described there https://stackoverflow.com/questions/21741880/how-do-you-create-new-windows-workspace-with-tfs-command-line-client-that-is-run
I'm trying to create workspace 

    /home/myuser/TEE-CLC-14.135.0/tf workspace -new SOMECORELIN -collection:http://tfsms.company.local/tfs/DefaultCollection

nothing happens.

then I'm trying to view workspace created, like:

    /home/myuser/TEE-CLC-14.135.0/tf workspaces
Result is: 

> No local workspaces found.

WSL has access to TFS server.

What is wrong? Maybe there was someone from you who had an experience or a similar problem, please help?

    java --version
    openjdk 11.0.9.1 2020-11-04
    OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
    OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

Have a nice day.

**Comment by loviji** [comment]
[leo-liu-msft](https://stackoverflow.com/users/7460777/leo-liu-msft) from stackoverflow advice me to resolve this issue like this:

There is an issue on the agent's TEE version before 14.135(github.com/Microsoft/team-explorer-everywhere/releases), To resolve that issue, we need update the TEE to 14.135 and copy two files ( slf4j-api-1.7.19.jar and slf4j-log4j12-1.7.19.jar) into the lib directory of new TEE from the lib directory of previous Tee (14.134), please try to this to check if it helps you.

And this advice fixes issue.

**Comment by aucampia** [comment]
having same issue and the workaround works like a charm.

**Comment by aucampia** [comment]
Exact commands I used to install a working copy:

```bash
# get TEE version
tee_version=$(curl --silent https://api.github.com/repos/Microsoft/team-explorer-everywhere/releases/latest | jq -r .tag_name | tee /dev/stderr)

# create directory for TEE-CLC
mkdir -vp ~/.local/opt/TEE-CLC/

# Download and extract TEE-CLC
curl -L https://github.com/microsoft/team-explorer-everywhere/releases/download/${tee_version}/TEE-CLC-${tee_version}.zip \
  | bsdtar -xvf - --strip-components 1 -C ~/.local/opt/TEE-CLC/

# Get the slf4j jars from the previous version
curl -L https://github.com/microsoft/team-explorer-everywhere/releases/download/14.134.0/TEE-CLC-14.134.0.zip | bsdtar -xvf - --strip-components 2 -C ~/.local/opt/TEE-CLC/lib/ './*/lib/slf4j-*'

# make tf executable
chmod +x ~/.local/opt/TEE-CLC/tf
```

**Comment by aucampia** [comment]
@eric-milles what issue was this a duplicate of?

**Comment by eric-milles** [comment]
#323
