### ISSUE TITLE
Just after install, Error with TeamExplorer viewing all repositories (using Anypoint Studio)

### ISSUE THREAD

**Issue by jktusoy** [microsoft/team-explorer-everywhere#332]
After installing the plugin to AnyPointStudio (an IDE based from Eclipse), I encounter this issue 
_"An internal error occurred during: "Loading section 'All Repositories'".
Could not initialize class com.microsoft.tfs.client.common.git.json.JsonHelper"_

![Capture](https://user-images.githubusercontent.com/7711061/104504364-f304a780-55a7-11eb-8dee-648d5bfb441b.PNG)

I check if that class exist in the plugins folder, It's not there. What should I do to fix this issue? 
![ref1](https://user-images.githubusercontent.com/7711061/104504660-66a6b480-55a8-11eb-930d-0f2099c718be.PNG)

**Comment by eric-milles** [comment]
Can you try the latest release and if the error still occurs, go to the Error Log view and report the full exception?
