### ISSUE TITLE
Unable to connect to TFS from within Eclipse

### ISSUE THREAD

**Issue by RaghavanMohanTR** [microsoft/team-explorer-everywhere#339]
Hello Team,

We are unable to connect to TFS (Azure DevOps) repository from within Eclipse. Every time when we connect to a project, refreshing the metadata gets struck at 40% and does not proceed further. This issue is occurring with latest version of the TEE CLC plugin for all versions of Eclipse tool. We have tried downgrading Eclipse and TFS plugin version used, clearing Eclipse cache, etc. but the issue is still occurring. Screenshots attached for more reference. Can someone suggest how to resolve this issue?

![image](https://user-images.githubusercontent.com/60435905/143897105-9d93259c-df5b-4a5d-8d81-83b93df1fca2.png)

We were able to connect to TFS repositories using an older version of Eclipse (2020-03) and TFS plugin version TFSEclipsePlugin-UpdateSiteArchive-10.1.0.2011121402.zip. However view History option is giving Null pointer exception.

![image](https://user-images.githubusercontent.com/60435905/143890795-16bfe307-2793-4d14-8574-e78d52ef27b3.png)

**Comment by eric-milles** [comment]
See #310
