### ISSUE TITLE
It is not possible to edit the workspace (set the status to Active / Cloaked or insert Source Control Folder and Local Folder)

### ISSUE THREAD

**Issue by grachchr** [microsoft/team-explorer-everywhere#344]
## Describe the bug
It is not possible to edit the workspace. I can't set the status to Active or Cloaked. Nor can I add Source Control Folder and Local Folder
with the browse menu.
It is only possible if Status, Source Control Folder and Local Folder are previously listed in a text document and the content of this text document is pasted into the Working Folders area via copy/paste.

The browse functionality is missing (for Status, Source Control Folder and Local Folder ).
The button is also not visible.
![Eclipse_Tfs_NoEditWorkspace](https://user-images.githubusercontent.com/80275938/166742534-98444b19-6990-457c-9732-19f724149576.JPG)

//--------------------------------------
// This is the configuration that works
//--------------------------------------
OS: Debian 10 (Buster)
Eclipse: Version: **2020-06 (4.16.0)** Build id: 20200615-1200
Team Explorer Everywhere: **14.134**.0.201804261733

## Useful information (current configuration)

OS: Debian 11 (Bullseye)
Eclipse: Version: **2022-03 (4.23.0)** Build id:20220310-1457
Team Explorer Everywhere: **14.137**.0.202203231501

Tested with:
- openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
- openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)

**Comment by eric-milles** [comment]
I am getting:
```
java.lang.NoClassDefFoundError: org/eclipse/jface/util/Assert
	at com.microsoft.tfs.client.common.ui.framework.celleditor.TextWithDialogCellEditor.doSetValue(TextWithDialogCellEditor.java:180)
	at org.eclipse.jface.viewers.CellEditor.setValue(CellEditor.java:853)
	...
```
