### ISSUE TITLE
Can we remove Log4J 1.2.x Jar as Log4J 1.2.x is EOL?

### ISSUE THREAD

**Issue by abhishekmurarka007** [microsoft/team-explorer-everywhere#351]
Hi Team,

Since Log4J 1.2.x is EOL, is it possible to replace the Log4j with latest version or remove it completely?
We are getting Security alerts since Log4J 12.x is EOL.

**Comment by Squire136** [comment]
Log4 1.2.x is more than EOL, it is riddled with security vulnerabilities. Please rev to log4j-2.19.0 or higher (https://logging.apache.org/log4j/2.x/download.html).

**Comment by rohan2001** [comment]
Can some one provide steps to replace jar file for log4j on Linux
log4j-1.2.14.jar

**Comment by UmmerS** [comment]
We are getting Security alerts since Log4J 12.x is EOL. 
Any alternate solution do suggest 
I truly appreciate your help.
