### ISSUE TITLE
Update Log4j 1.2 to 2.3.2

### ISSUE THREAD

**Issue by rohan2001** [microsoft/team-explorer-everywhere#354]

**Comment by rohan2001** [comment]
We see Log4j 1.x is used which is causing tf to be vulnerable. Is there way to mitigate this

**Comment by UmmerS** [comment]
> We see Log4j 1.x is used which is causing tf to be vulnerable. Is there way to mitigate this

@rohan2001  have you got any solution for this issue.

**Comment by rohan2001** [comment]
@UmmerS  I havent got the solution yet.
Do let me know if there is any alternative available

**Comment by UmmerS** [comment]
@eric-milles please update log4j for latest version and release new version 14.138.0
Many are facing this issue
Thanks in advance.

**Comment by UmmerS** [comment]
@eric-milles
Thanks for update to log4j-1.2.17.jar
But log4j-1.2.17.jar is also vulnerable need to migrate to Log4j v2

**Comment by rohan2001** [comment]
@UmmerS  @eric-milles  Steps to mitigate vulnerability

**Comment by eric-milles** [comment]
a release is coming shortly
