### ISSUE TITLE
Only SSL

### ISSUE THREAD

**Issue by mindgen** [microsoft/team-explorer-everywhere#68]
TFE don't work with TLS

**Comment by paulvi** [comment]
As from https://en.wikipedia.org/wiki/Transport_Layer_Security SSL is not considered secure any more

**Comment by sander** [comment]
https://github.com/Microsoft/team-explorer-everywhere/blob/294180f7a4d471fb9a2bfda012fb420bd404c499/source/com.microsoft.tfs.core/src/com/microsoft/tfs/core/config/httpclient/internal/DefaultSSLProtocolSocketFactory.java#L131 

`"SSL"` is hardcoded, maybe it works if you change that to `"TLSv1.2"` as per [Standard Algorithm Name Documentation](https://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html#SSLContext)?

**Comment by eric-milles** [comment]
Looks like you can set via system property `com.microsoft.tfs.core.config.httpclient.sslsocketfactory.sslprotocol`

https://github.com/Microsoft/team-explorer-everywhere/blob/master/source/com.microsoft.tfs.core/src/com/microsoft/tfs/core/config/httpclient/internal/DefaultSSLProtocolSocketFactory.java#L163
