### ISSUE TITLE
Publish TFS SDK in the maven central repository

### ISSUE THREAD

**Issue by davidt** [microsoft/team-explorer-everywhere#83]
Right now it's fairly difficult to consume the TFS SDK as part of an automatic build that uses maven or ivy for dependency management. Especially now that the SDK is open source, it would be fantastic if it was as easy as `<dependency org="com.microsoft" name="com.microsoft.tfs.sdk" rev="14.0.3" />`

**Comment by DavidStaheli** [comment]
Thanks for this important suggestion, David.  We should have it in Maven Central very soon (fingers crossed).

**Comment by davidt** [comment]
Wonderful news. Thanks for the quick response.

**Comment by DavidStaheli** [comment]
Hi David, unfortunately we hit roadblocks with the SDK's use of native OS libraries on the side and in its current Ant build form.  It's going to take us longer than expected to make the SDK compatible with Maven Central as a single JAR.  In the meantime, and you probably already know this, you could temporarily reference the SDK as a Maven dependency by declaring the source repository as a file path/share where the SDK is located.

**Comment by Quirexx** [comment]
Any status update on the maven integration?

**Comment by DavidStaheli** [comment]
There is nothing new to report, but it is still something we are anxious to do as soon as possible.

**Comment by kravtsov-viktor** [comment]
Hello guys!
Any new about maven integration for TFS java SDK ?

**Comment by viktorKhan** [comment]
Any update about this topic?
Currently we have a lot of problems with dependencies collisions between TFS library and other libraries we use in our project, specially with jackson and httpclient libraries.
If you don't have a plan to "mavenize" this library, is there any way to exclude these dependencies from TFS?
Another question, are these third party libraries customized in some way or just included in the jar as they are?

Thanks in advance.
