### ISSUE TITLE
TEE 14.0.4: Update the first or second version digit to reflect the major auth changes

### ISSUE THREAD

**Issue by ramoas** [microsoft/team-explorer-everywhere#94]
@yacaovsnc , @AlexRukhlin , as we discussed via email (during course of Issue #85 ), given all the major, mandatory authentication changes in TEE 14.0.3+ (with more planned for TEE 14.0.4), for clearer communication to users of their significance, I suggest making the next TEE version much more than a minor version increment over TEE 14.0.3.  That is, do not use "TEE 14.0.4".  If at all possible, change the first version digit -- say to TEE 15.0.x -- or the second version digit -- say to TEE 14.5.x, or at least to TEE 14.1.x.

The authentication changes alone are just way too significant and have too many subtle consequences to have the appearance of a minor servicing release that only includes bug fixes and/or improved stability and compatibility.  This is why I did not hesitate before upgrading from TEE 14.0.1 / TEE 14.0.2 to TEE 14.0.3 -- I just did not expect TEE 14.0.3 to drop support for my VSTS alternate credentials and cause me so much trouble (= Issue #85).

**Comment by DavidStaheli** [comment]
Thanks for the suggestion, ramoas.  Considering in next release plans...
